/*
 Navicat Premium Data Transfer

 Source Server         : VANGUARDIA
 Source Server Type    : Oracle
 Source Server Version : 110200
 Source Schema         : JC

 Target Server Type    : Oracle
 Target Server Version : 110200
 File Encoding         : 65001

 Date: 10/06/2021 03:17:32
*/


-- ----------------------------
-- Table structure for ACTIVIDADES_CLASES
-- ----------------------------
DROP TABLE "JC"."ACTIVIDADES_CLASES";
CREATE TABLE "JC"."ACTIVIDADES_CLASES" (
  "ID" NUMBER(38,30) NOT NULL,
  "FK_SECCION" NUMBER(38,30),
  "SEMANA" NUMBER(38,30),
  "FECHA_ENTREGA" DATE,
  "ACTIVIDAD" VARCHAR2(255 BYTE),
  "FK_MODALIDAD" NUMBER(38,30),
  "VALOR" NUMBER(38,30)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of ACTIVIDADES_CLASES
-- ----------------------------

-- ----------------------------
-- Table structure for ALUMNOS
-- ----------------------------
DROP TABLE "JC"."ALUMNOS";
CREATE TABLE "JC"."ALUMNOS" (
  "ID" NUMBER(38,30) NOT NULL,
  "IDENTIDAD" VARCHAR2(20 BYTE) NOT NULL,
  "NOMBRES" VARCHAR2(30 BYTE) NOT NULL,
  "APELLIDOS" VARCHAR2(30 BYTE) NOT NULL,
  "TELEFONO" VARCHAR2(20 BYTE) NOT NULL,
  "DIRECCION" VARCHAR2(20 BYTE) NOT NULL,
  "LATITUD" BINARY_DOUBLE NOT NULL,
  "LONGITUD" BINARY_DOUBLE NOT NULL,
  "FECHA_NACIMIENTO" DATE NOT NULL,
  "FK_USUARIO" NUMBER
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of ALUMNOS
-- ----------------------------

-- ----------------------------
-- Table structure for ALUMNOS_SECCIONES
-- ----------------------------
DROP TABLE "JC"."ALUMNOS_SECCIONES";
CREATE TABLE "JC"."ALUMNOS_SECCIONES" (
  "ID" NUMBER(38,30) NOT NULL,
  "FK_SEECION" NUMBER(38,30),
  "FK_ALUMNO" NUMBER(38,30),
  "ACUMULATIVO" BINARY_DOUBLE,
  "EXAMEN" BINARY_DOUBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of ALUMNOS_SECCIONES
-- ----------------------------

-- ----------------------------
-- Table structure for ARREGLOS_PAGOS
-- ----------------------------
DROP TABLE "JC"."ARREGLOS_PAGOS";
CREATE TABLE "JC"."ARREGLOS_PAGOS" (
  "ID" NUMBER(38,30) NOT NULL,
  "FK_ESTUDIANTE" NUMBER(38,30),
  "FECHA" DATE,
  "VALOR_ADEUDADO" BINARY_DOUBLE,
  "VALOR_PROMETIDO_PAGO" BINARY_DOUBLE,
  "VALOR_PAGADO" BINARY_DOUBLE,
  "FECHA_PAGO" DATE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of ARREGLOS_PAGOS
-- ----------------------------

-- ----------------------------
-- Table structure for CARRERAS
-- ----------------------------
DROP TABLE "JC"."CARRERAS";
CREATE TABLE "JC"."CARRERAS" (
  "ID" NUMBER(38,30) NOT NULL,
  "NOMBRE_CARRERA" VARCHAR2(255 BYTE) NOT NULL,
  "FK_PLAN" NUMBER(38,30),
  "FK_ORIENTACION" NUMBER(38,30)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of CARRERAS
-- ----------------------------

-- ----------------------------
-- Table structure for CARRERAS_ALUMNOS
-- ----------------------------
DROP TABLE "JC"."CARRERAS_ALUMNOS";
CREATE TABLE "JC"."CARRERAS_ALUMNOS" (
  "FK_IDENTIDAD_ALUMNO" NUMBER(38,30),
  "FK_CARRERA" NUMBER(38,30),
  "CUENTA" VARCHAR2(20 BYTE),
  "FECHA_INGRESO" DATE,
  "FK_MODALIDAD" NUMBER(38,30),
  "ID" NUMBER(38,30) NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of CARRERAS_ALUMNOS
-- ----------------------------

-- ----------------------------
-- Table structure for CLASES
-- ----------------------------
DROP TABLE "JC"."CLASES";
CREATE TABLE "JC"."CLASES" (
  "ID" NUMBER(38,30) NOT NULL,
  "NOMBRE_CLASE" VARCHAR2(60 BYTE),
  "UNIDADES_VALORATIVAS" NUMBER(38,30),
  "CODIGO_CLASE" VARCHAR2(10 BYTE),
  "VALOR_CLASE" NUMBER(38,30)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of CLASES
-- ----------------------------

-- ----------------------------
-- Table structure for CLASES_PLANES_ESTUDIO
-- ----------------------------
DROP TABLE "JC"."CLASES_PLANES_ESTUDIO";
CREATE TABLE "JC"."CLASES_PLANES_ESTUDIO" (
  "FK_PLAN" NUMBER(38,30),
  "FK_CLASE" NUMBER(38,30),
  "ID" NUMBER(38,30) NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of CLASES_PLANES_ESTUDIO
-- ----------------------------

-- ----------------------------
-- Table structure for FORO_SECCIONES
-- ----------------------------
DROP TABLE "JC"."FORO_SECCIONES";
CREATE TABLE "JC"."FORO_SECCIONES" (
  "ID" NUMBER(38,30) NOT NULL,
  "FK_SECCION" NUMBER(38,30),
  "FK_MAESTRO" NUMBER(38,30),
  "TITULO" VARCHAR2(255 BYTE),
  "DESCRIPCION" VARCHAR2(255 BYTE),
  "VALOR" NUMBER(38,30)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of FORO_SECCIONES
-- ----------------------------

-- ----------------------------
-- Table structure for INFO_UNIVERIDADES
-- ----------------------------
DROP TABLE "JC"."INFO_UNIVERIDADES";
CREATE TABLE "JC"."INFO_UNIVERIDADES" (
  "ID" NUMBER(38,30) NOT NULL,
  "NOMRE" VARCHAR2(60 BYTE) NOT NULL,
  "MISION" VARCHAR2(250 BYTE) NOT NULL,
  "VISION" VARCHAR2(250 BYTE) NOT NULL,
  "OBJETIVOS" VARCHAR2(250 BYTE) NOT NULL,
  "POLITICAS" VARCHAR2(250 BYTE) NOT NULL,
  "LOGO" VARCHAR2(100 BYTE) NOT NULL,
  "ORGANIGRAMA" VARCHAR2(100 BYTE) NOT NULL,
  "LATITUD" BINARY_DOUBLE NOT NULL,
  "LONJITUD" BINARY_DOUBLE NOT NULL,
  "DIRECCION_POSTAL" VARCHAR2(250 BYTE) NOT NULL,
  "EMAIL" VARCHAR2(60 BYTE) NOT NULL,
  "TELEFONO_1" VARCHAR2(15 BYTE),
  "TELEFONO_2" VARCHAR2(15 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of INFO_UNIVERIDADES
-- ----------------------------
INSERT INTO "JC"."INFO_UNIVERIDADES" VALUES ('1', 'CENTRO TECNOLOGICO UNIVERSITARIO', 'Misión
Formar profesionales íntegros y competentes mediante una modalidad educativa de calidad, innovadora y accesible, con uso intensivo de tecnología, que genere crecimiento personal para la transformación de la sociedad.', 'Visión
Ser una universidad referente a nivel internacional en la formación de profesionales íntegros, competentes y emprendedores, que contribuyan al desarrollo y transformación de la sociedad.', 'Fortalecer una cultura de calidad mediante el desarrollo de competencias de los colaboradores académicos y administrativos.', 'En la Universidad Tecnológica Centroamericana, UNITEC, nos comprometemos en la formación de profesionales competentes, con un enfoque vinculado con la sociedad, en el marco de una cultura de calidad basada en la mejora continua y la excelencia.', 'logo.png', 'organigrama.png', '14.104728812830295', '-87.18608811086162', 'Col. La Campaña, atrás del Hospital San Felipe', 'admisionesceutec@unitec.edu', ' +504 2564-7400', '+504 9667-0124');

-- ----------------------------
-- Table structure for MAESTROS
-- ----------------------------
DROP TABLE "JC"."MAESTROS";
CREATE TABLE "JC"."MAESTROS" (
  "ID" NUMBER(38,30) NOT NULL,
  "IDENTIDAD" VARCHAR2(20 BYTE) NOT NULL,
  "NOMBRES" VARCHAR2(30 BYTE) NOT NULL,
  "APELLIDOS" VARCHAR2(30 BYTE) NOT NULL,
  "TELEFONO" VARCHAR2(20 BYTE) NOT NULL,
  "DIRECCION" VARCHAR2(20 BYTE) NOT NULL,
  "LATITUD" BINARY_DOUBLE NOT NULL,
  "LONGITUD" BINARY_DOUBLE NOT NULL,
  "FECHA_NACIMIENTO" DATE NOT NULL,
  "FK_USUARIO" NUMBER,
  "FOTO_URL" VARCHAR2(255 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of MAESTROS
-- ----------------------------

-- ----------------------------
-- Table structure for MODALIDADES
-- ----------------------------
DROP TABLE "JC"."MODALIDADES";
CREATE TABLE "JC"."MODALIDADES" (
  "ID" NUMBER(38,30) NOT NULL,
  "MODALIDAD" VARCHAR2(50 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of MODALIDADES
-- ----------------------------

-- ----------------------------
-- Table structure for ORIENTACIONES
-- ----------------------------
DROP TABLE "JC"."ORIENTACIONES";
CREATE TABLE "JC"."ORIENTACIONES" (
  "ID" NUMBER(38,30) NOT NULL,
  "ORIENTACION" VARCHAR2(50 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of ORIENTACIONES
-- ----------------------------

-- ----------------------------
-- Table structure for PAGOS
-- ----------------------------
DROP TABLE "JC"."PAGOS";
CREATE TABLE "JC"."PAGOS" (
  "ID" NUMBER(38,30) NOT NULL,
  "FK_ALUMNO" NUMBER(38,30),
  "FECHA" DATE,
  "PAGO" BINARY_DOUBLE,
  "DESCRIPCION" VARCHAR2(255 BYTE),
  "TOTAL" BINARY_DOUBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of PAGOS
-- ----------------------------

-- ----------------------------
-- Table structure for PERIODO_ACTUAL
-- ----------------------------
DROP TABLE "JC"."PERIODO_ACTUAL";
CREATE TABLE "JC"."PERIODO_ACTUAL" (
  "ID" NUMBER NOT NULL,
  "ANO" NUMBER,
  "MODULO" NUMBER
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of PERIODO_ACTUAL
-- ----------------------------

-- ----------------------------
-- Table structure for PERSONAL_REGISTO
-- ----------------------------
DROP TABLE "JC"."PERSONAL_REGISTO";
CREATE TABLE "JC"."PERSONAL_REGISTO" (
  "ID" NUMBER(38,30) NOT NULL,
  "IDENTIDAD" VARCHAR2(20 BYTE) NOT NULL,
  "NOMBRES" VARCHAR2(30 BYTE) NOT NULL,
  "APELLIDOS" VARCHAR2(30 BYTE) NOT NULL,
  "TELEFONO" VARCHAR2(20 BYTE) NOT NULL,
  "DIRECCION" VARCHAR2(20 BYTE) NOT NULL,
  "LATITUD" BINARY_DOUBLE NOT NULL,
  "LONGITUD" BINARY_DOUBLE NOT NULL,
  "FECHA_NACIMIENTO" DATE NOT NULL,
  "FK_USUARIO" NUMBER,
  "FOTO_URL" VARCHAR2(255 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of PERSONAL_REGISTO
-- ----------------------------

-- ----------------------------
-- Table structure for PLANES_ESTUDIOS
-- ----------------------------
DROP TABLE "JC"."PLANES_ESTUDIOS";
CREATE TABLE "JC"."PLANES_ESTUDIOS" (
  "ID" NUMBER(38,30) NOT NULL,
  "AÑO_VIGENCIA" NUMBER(38,30),
  "AÑO_CIERRE" NUMBER(38,30)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of PLANES_ESTUDIOS
-- ----------------------------

-- ----------------------------
-- Table structure for PREGUNTAS_BREVES
-- ----------------------------
DROP TABLE "JC"."PREGUNTAS_BREVES";
CREATE TABLE "JC"."PREGUNTAS_BREVES" (
  "ID" NUMBER(38,30) NOT NULL,
  "PREGUNTA" VARCHAR2(255 BYTE),
  "RESPUESTA" VARCHAR2(255 BYTE),
  "VALOR" NUMBER(38,30)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of PREGUNTAS_BREVES
-- ----------------------------

-- ----------------------------
-- Table structure for PREGUNTAS_MULTIPLES
-- ----------------------------
DROP TABLE "JC"."PREGUNTAS_MULTIPLES";
CREATE TABLE "JC"."PREGUNTAS_MULTIPLES" (
  "ID" NUMBER(38,30) NOT NULL,
  "PREGUNTA" VARCHAR2(255 BYTE),
  "OPCION_A" VARCHAR2(255 BYTE),
  "OPCION_B" VARCHAR2(255 BYTE),
  "OPCION_C" VARCHAR2(255 BYTE),
  "OPCION_D" VARCHAR2(255 BYTE),
  "RESPUESTA" NUMBER(38,30)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of PREGUNTAS_MULTIPLES
-- ----------------------------

-- ----------------------------
-- Table structure for PREGUNTAS_PRUEBAS_SECCIONES
-- ----------------------------
DROP TABLE "JC"."PREGUNTAS_PRUEBAS_SECCIONES";
CREATE TABLE "JC"."PREGUNTAS_PRUEBAS_SECCIONES" (
  "ID" NUMBER(38,30) NOT NULL,
  "FK_PREGUNTA_VOF" NUMBER(38,30),
  "FK_PRUEBA_SECCION" NUMBER(38,30),
  "FK_PREGUNTA_MULT" NUMBER(38,30),
  "FK_PREGUNTA_BREVE" NUMBER(38,30)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of PREGUNTAS_PRUEBAS_SECCIONES
-- ----------------------------

-- ----------------------------
-- Table structure for PREGUNTAS_VOFS
-- ----------------------------
DROP TABLE "JC"."PREGUNTAS_VOFS";
CREATE TABLE "JC"."PREGUNTAS_VOFS" (
  "ID" NUMBER(38,30) NOT NULL,
  "VERDADERO" NUMBER(38,30),
  "FALSO" NUMBER(38,30),
  "CORRECTA" NUMBER(38,30),
  "PREGUNTA" VARCHAR2(255 BYTE),
  "VALOR" NUMBER(38,30)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of PREGUNTAS_VOFS
-- ----------------------------

-- ----------------------------
-- Table structure for PRUEBAS_ALUMNOS
-- ----------------------------
DROP TABLE "JC"."PRUEBAS_ALUMNOS";
CREATE TABLE "JC"."PRUEBAS_ALUMNOS" (
  "ID" NUMBER(38,30) NOT NULL,
  "FK_PRUEBA_SECCION" NUMBER(38,30),
  "FK_ALUMNO" NUMBER(38,30),
  "NOTA" NUMBER(38,30)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of PRUEBAS_ALUMNOS
-- ----------------------------

-- ----------------------------
-- Table structure for PRUEBAS_SECCIONES
-- ----------------------------
DROP TABLE "JC"."PRUEBAS_SECCIONES";
CREATE TABLE "JC"."PRUEBAS_SECCIONES" (
  "ID" NUMBER(38,30) NOT NULL,
  "FK_SECCION" NUMBER(38,30),
  "FK_MAESTRO" NUMBER(38,30),
  "FECHA" DATE,
  "DURACION" BINARY_DOUBLE,
  "HORA_INICIO" NUMBER(38,30),
  "HORA_FINAL" NUMBER(38,30),
  "NOMBRE" VARCHAR2(50 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of PRUEBAS_SECCIONES
-- ----------------------------

-- ----------------------------
-- Table structure for RECLAMOS
-- ----------------------------
DROP TABLE "JC"."RECLAMOS";
CREATE TABLE "JC"."RECLAMOS" (
  "ID" NUMBER(38,30) NOT NULL,
  "FK_DOCENTE" NUMBER(38,30),
  "FK_TIPO_RECLAMO" NUMBER(38,30),
  "DESCRIPCION" VARCHAR2(255 BYTE),
  "FECHA_RECLAMO" DATE,
  "RESPUESTA" VARCHAR2(255 BYTE),
  "FECHA_RESPUESTA" DATE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of RECLAMOS
-- ----------------------------

-- ----------------------------
-- Table structure for RESPUESTAS_BREVES
-- ----------------------------
DROP TABLE "JC"."RESPUESTAS_BREVES";
CREATE TABLE "JC"."RESPUESTAS_BREVES" (
  "ID" NUMBER(38,30) NOT NULL,
  "RESPUESTA" VARCHAR2(255 BYTE),
  "NOTA" NUMBER(38,30)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of RESPUESTAS_BREVES
-- ----------------------------

-- ----------------------------
-- Table structure for RESPUESTAS_FOROS
-- ----------------------------
DROP TABLE "JC"."RESPUESTAS_FOROS";
CREATE TABLE "JC"."RESPUESTAS_FOROS" (
  "ID" NUMBER(38,30) NOT NULL,
  "FK_FORO" NUMBER(38,30),
  "FK_ALUMNO" NUMBER(38,30),
  "TITULO" VARCHAR2(255 BYTE),
  "DESCRIPCION" VARCHAR2(255 BYTE),
  "VALOR" NUMBER(38,30)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of RESPUESTAS_FOROS
-- ----------------------------

-- ----------------------------
-- Table structure for RESPUESTAS_MULTIPLES
-- ----------------------------
DROP TABLE "JC"."RESPUESTAS_MULTIPLES";
CREATE TABLE "JC"."RESPUESTAS_MULTIPLES" (
  "ID" NUMBER(38,30) NOT NULL,
  "RESPUESTA" NUMBER(38,30),
  "NOTA" NUMBER(38,30)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of RESPUESTAS_MULTIPLES
-- ----------------------------

-- ----------------------------
-- Table structure for RESPUESTAS_PRUEBAS_ALUMNOS
-- ----------------------------
DROP TABLE "JC"."RESPUESTAS_PRUEBAS_ALUMNOS";
CREATE TABLE "JC"."RESPUESTAS_PRUEBAS_ALUMNOS" (
  "ID" NUMBER(38,30) NOT NULL,
  "FK_RESPUESTA_ALUMNO" NUMBER(38,30),
  "FK_RESPUESTA_VOF" NUMBER(38,30),
  "FK_RESPUESTA_BREVE" NUMBER(38,30),
  "FK_RESPUESTA_MULTI" NUMBER(38,30)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of RESPUESTAS_PRUEBAS_ALUMNOS
-- ----------------------------

-- ----------------------------
-- Table structure for RESPUESTAS_VOFS
-- ----------------------------
DROP TABLE "JC"."RESPUESTAS_VOFS";
CREATE TABLE "JC"."RESPUESTAS_VOFS" (
  "ID" NUMBER(38,30) NOT NULL,
  "RESPUESTA" NUMBER(38,30),
  "NOTA" NUMBER(38,30)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of RESPUESTAS_VOFS
-- ----------------------------

-- ----------------------------
-- Table structure for SALDOS
-- ----------------------------
DROP TABLE "JC"."SALDOS";
CREATE TABLE "JC"."SALDOS" (
  "ID" NUMBER(38,30) NOT NULL,
  "FK_ALUMNO" NUMBER(38,30),
  "FECHA" DATE,
  "SALDO" BINARY_DOUBLE,
  "DESCRIPCION" VARCHAR2(255 BYTE),
  "TOTAL" BINARY_DOUBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of SALDOS
-- ----------------------------

-- ----------------------------
-- Table structure for SECCIONES
-- ----------------------------
DROP TABLE "JC"."SECCIONES";
CREATE TABLE "JC"."SECCIONES" (
  "ID" NUMBER(38,30) NOT NULL,
  "FK_CODIGO_CLASE" NUMBER(38,30),
  "SECCION" VARCHAR2(10 BYTE),
  "HORA" NVARCHAR2(15),
  "AULA" VARCHAR2(30 BYTE),
  "DIAS" VARCHAR2(20 BYTE),
  "CUPOS" NUMBER(38,30),
  "FK_DOCENTE" NUMBER(38,30),
  "FK_SEDE" NUMBER(38,30),
  "FK_PERIODO_ACTUAL" NUMBER(38,30),
  "FK_MODALIDAD" NUMBER(38,30),
  "ACUMULATIVOS" NUMBER(38,30),
  "EXAMEN" NUMBER(38,30)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of SECCIONES
-- ----------------------------

-- ----------------------------
-- Table structure for SEDES
-- ----------------------------
DROP TABLE "JC"."SEDES";
CREATE TABLE "JC"."SEDES" (
  "ID" NUMBER(38,30) NOT NULL,
  "FK_ID_UNIVERSIDAD" NUMBER(38,30),
  "NOMBRE_SEDE" VARCHAR2(50 BYTE),
  "DIRECCION" VARCHAR2(255 BYTE),
  "TELEFONO" VARCHAR2(15 BYTE),
  "LATITUD" BINARY_DOUBLE,
  "LONGITUD" BINARY_DOUBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of SEDES
-- ----------------------------

-- ----------------------------
-- Table structure for TAREAS_ALUMNOS
-- ----------------------------
DROP TABLE "JC"."TAREAS_ALUMNOS";
CREATE TABLE "JC"."TAREAS_ALUMNOS" (
  "ID" NUMBER(38,30) NOT NULL,
  "FK_TAREA" NUMBER(38,30),
  "FK_ALUMNO" NUMBER(38,30),
  "URL" VARCHAR2(255 BYTE),
  "NOTA" NUMBER(38,30),
  "COMENTARIO_ENTREGA" VARCHAR2(255 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of TAREAS_ALUMNOS
-- ----------------------------

-- ----------------------------
-- Table structure for TAREAS_SECCIONES
-- ----------------------------
DROP TABLE "JC"."TAREAS_SECCIONES";
CREATE TABLE "JC"."TAREAS_SECCIONES" (
  "ID" NUMBER(38,30) NOT NULL,
  "FK_SECCION" NUMBER(38,30),
  "TITULO" VARCHAR2(255 BYTE),
  "DESCRIPCION" VARCHAR2(255 BYTE),
  "VALOR" NUMBER(38,30),
  "FK_DOCENTE" NUMBER(38,30)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of TAREAS_SECCIONES
-- ----------------------------

-- ----------------------------
-- Table structure for TIPOS_DE_USUARIO
-- ----------------------------
DROP TABLE "JC"."TIPOS_DE_USUARIO";
CREATE TABLE "JC"."TIPOS_DE_USUARIO" (
  "TIPO_USUARIO" NUMBER(38,30) NOT NULL,
  "DESCRIPCION" VARCHAR2(30 BYTE) NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of TIPOS_DE_USUARIO
-- ----------------------------
INSERT INTO "JC"."TIPOS_DE_USUARIO" VALUES ('1', 'REGISTRO');
INSERT INTO "JC"."TIPOS_DE_USUARIO" VALUES ('2', 'MAESTRO');
INSERT INTO "JC"."TIPOS_DE_USUARIO" VALUES ('3', 'ALUMNO');

-- ----------------------------
-- Table structure for TIPOS_RECLAMOS
-- ----------------------------
DROP TABLE "JC"."TIPOS_RECLAMOS";
CREATE TABLE "JC"."TIPOS_RECLAMOS" (
  "ID" NUMBER(38,30) NOT NULL,
  "DESCRIPCION" VARCHAR2(255 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of TIPOS_RECLAMOS
-- ----------------------------

-- ----------------------------
-- Table structure for USUARIOS
-- ----------------------------
DROP TABLE "JC"."USUARIOS";
CREATE TABLE "JC"."USUARIOS" (
  "CORREO" VARCHAR2(50 BYTE) NOT NULL,
  "PASSWORD" VARCHAR2(100 BYTE) NOT NULL,
  "FK_TIPO_USUARIO" NUMBER(38,30) NOT NULL,
  "ESTADO" CHAR(1 BYTE) NOT NULL,
  "ID" NUMBER NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of USUARIOS
-- ----------------------------

-- ----------------------------
-- Primary Key structure for table ACTIVIDADES_CLASES
-- ----------------------------
ALTER TABLE "JC"."ACTIVIDADES_CLASES" ADD CONSTRAINT "SYS_C007007" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table ACTIVIDADES_CLASES
-- ----------------------------
ALTER TABLE "JC"."ACTIVIDADES_CLASES" ADD CONSTRAINT "SYS_C007006" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table ALUMNOS
-- ----------------------------
ALTER TABLE "JC"."ALUMNOS" ADD CONSTRAINT "SYS_C007008" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table ALUMNOS
-- ----------------------------
ALTER TABLE "JC"."ALUMNOS" ADD CONSTRAINT "SYS_C006997" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."ALUMNOS" ADD CONSTRAINT "SYS_C006998" CHECK ("IDENTIDAD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."ALUMNOS" ADD CONSTRAINT "SYS_C006999" CHECK ("NOMBRES" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."ALUMNOS" ADD CONSTRAINT "SYS_C007000" CHECK ("APELLIDOS" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."ALUMNOS" ADD CONSTRAINT "SYS_C007001" CHECK ("TELEFONO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."ALUMNOS" ADD CONSTRAINT "SYS_C007002" CHECK ("DIRECCION" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."ALUMNOS" ADD CONSTRAINT "SYS_C007003" CHECK ("LATITUD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."ALUMNOS" ADD CONSTRAINT "SYS_C007004" CHECK ("LONGITUD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."ALUMNOS" ADD CONSTRAINT "SYS_C007005" CHECK ("FECHA_NACIMIENTO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table ALUMNOS_SECCIONES
-- ----------------------------
ALTER TABLE "JC"."ALUMNOS_SECCIONES" ADD CONSTRAINT "SYS_C007013" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table ALUMNOS_SECCIONES
-- ----------------------------
ALTER TABLE "JC"."ALUMNOS_SECCIONES" ADD CONSTRAINT "SYS_C007009" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table ARREGLOS_PAGOS
-- ----------------------------
ALTER TABLE "JC"."ARREGLOS_PAGOS" ADD CONSTRAINT "SYS_C007014" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table ARREGLOS_PAGOS
-- ----------------------------
ALTER TABLE "JC"."ARREGLOS_PAGOS" ADD CONSTRAINT "SYS_C007010" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table CARRERAS
-- ----------------------------
ALTER TABLE "JC"."CARRERAS" ADD CONSTRAINT "SYS_C007015" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table CARRERAS
-- ----------------------------
ALTER TABLE "JC"."CARRERAS" ADD CONSTRAINT "SYS_C007011" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."CARRERAS" ADD CONSTRAINT "SYS_C007012" CHECK ("NOMBRE_CARRERA" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table CARRERAS_ALUMNOS
-- ----------------------------
ALTER TABLE "JC"."CARRERAS_ALUMNOS" ADD CONSTRAINT "SYS_C007017" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table CARRERAS_ALUMNOS
-- ----------------------------
ALTER TABLE "JC"."CARRERAS_ALUMNOS" ADD CONSTRAINT "SYS_C007016" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table CLASES
-- ----------------------------
ALTER TABLE "JC"."CLASES" ADD CONSTRAINT "SYS_C007019" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table CLASES
-- ----------------------------
ALTER TABLE "JC"."CLASES" ADD CONSTRAINT "SYS_C007018" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table CLASES_PLANES_ESTUDIO
-- ----------------------------
ALTER TABLE "JC"."CLASES_PLANES_ESTUDIO" ADD CONSTRAINT "SYS_C007021" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table CLASES_PLANES_ESTUDIO
-- ----------------------------
ALTER TABLE "JC"."CLASES_PLANES_ESTUDIO" ADD CONSTRAINT "SYS_C007020" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table FORO_SECCIONES
-- ----------------------------
ALTER TABLE "JC"."FORO_SECCIONES" ADD CONSTRAINT "SYS_C007023" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table FORO_SECCIONES
-- ----------------------------
ALTER TABLE "JC"."FORO_SECCIONES" ADD CONSTRAINT "SYS_C007022" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table INFO_UNIVERIDADES
-- ----------------------------
ALTER TABLE "JC"."INFO_UNIVERIDADES" ADD CONSTRAINT "SYS_C007036" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table INFO_UNIVERIDADES
-- ----------------------------
ALTER TABLE "JC"."INFO_UNIVERIDADES" ADD CONSTRAINT "SYS_C007024" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."INFO_UNIVERIDADES" ADD CONSTRAINT "SYS_C007025" CHECK ("NOMRE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."INFO_UNIVERIDADES" ADD CONSTRAINT "SYS_C007026" CHECK ("MISION" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."INFO_UNIVERIDADES" ADD CONSTRAINT "SYS_C007027" CHECK ("VISION" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."INFO_UNIVERIDADES" ADD CONSTRAINT "SYS_C007028" CHECK ("OBJETIVOS" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."INFO_UNIVERIDADES" ADD CONSTRAINT "SYS_C007029" CHECK ("POLITICAS" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."INFO_UNIVERIDADES" ADD CONSTRAINT "SYS_C007030" CHECK ("LOGO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."INFO_UNIVERIDADES" ADD CONSTRAINT "SYS_C007031" CHECK ("ORGANIGRAMA" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."INFO_UNIVERIDADES" ADD CONSTRAINT "SYS_C007032" CHECK ("LATITUD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."INFO_UNIVERIDADES" ADD CONSTRAINT "SYS_C007033" CHECK ("LONJITUD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."INFO_UNIVERIDADES" ADD CONSTRAINT "SYS_C007034" CHECK ("DIRECCION_POSTAL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."INFO_UNIVERIDADES" ADD CONSTRAINT "SYS_C007035" CHECK ("EMAIL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table MAESTROS
-- ----------------------------
ALTER TABLE "JC"."MAESTROS" ADD CONSTRAINT "SYS_C007046" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table MAESTROS
-- ----------------------------
ALTER TABLE "JC"."MAESTROS" ADD CONSTRAINT "SYS_C007037" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."MAESTROS" ADD CONSTRAINT "SYS_C007038" CHECK ("IDENTIDAD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."MAESTROS" ADD CONSTRAINT "SYS_C007039" CHECK ("NOMBRES" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."MAESTROS" ADD CONSTRAINT "SYS_C007040" CHECK ("APELLIDOS" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."MAESTROS" ADD CONSTRAINT "SYS_C007041" CHECK ("TELEFONO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."MAESTROS" ADD CONSTRAINT "SYS_C007042" CHECK ("DIRECCION" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."MAESTROS" ADD CONSTRAINT "SYS_C007043" CHECK ("LATITUD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."MAESTROS" ADD CONSTRAINT "SYS_C007044" CHECK ("LONGITUD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."MAESTROS" ADD CONSTRAINT "SYS_C007045" CHECK ("FECHA_NACIMIENTO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table MODALIDADES
-- ----------------------------
ALTER TABLE "JC"."MODALIDADES" ADD CONSTRAINT "SYS_C007048" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table MODALIDADES
-- ----------------------------
ALTER TABLE "JC"."MODALIDADES" ADD CONSTRAINT "SYS_C007047" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table ORIENTACIONES
-- ----------------------------
ALTER TABLE "JC"."ORIENTACIONES" ADD CONSTRAINT "SYS_C007050" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table ORIENTACIONES
-- ----------------------------
ALTER TABLE "JC"."ORIENTACIONES" ADD CONSTRAINT "SYS_C007049" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table PAGOS
-- ----------------------------
ALTER TABLE "JC"."PAGOS" ADD CONSTRAINT "SYS_C007052" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table PAGOS
-- ----------------------------
ALTER TABLE "JC"."PAGOS" ADD CONSTRAINT "SYS_C007051" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table PERIODO_ACTUAL
-- ----------------------------
ALTER TABLE "JC"."PERIODO_ACTUAL" ADD CONSTRAINT "SYS_C007117" PRIMARY KEY ("ID");

-- ----------------------------
-- Primary Key structure for table PERSONAL_REGISTO
-- ----------------------------
ALTER TABLE "JC"."PERSONAL_REGISTO" ADD CONSTRAINT "SYS_C007062" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table PERSONAL_REGISTO
-- ----------------------------
ALTER TABLE "JC"."PERSONAL_REGISTO" ADD CONSTRAINT "SYS_C007053" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."PERSONAL_REGISTO" ADD CONSTRAINT "SYS_C007054" CHECK ("IDENTIDAD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."PERSONAL_REGISTO" ADD CONSTRAINT "SYS_C007055" CHECK ("NOMBRES" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."PERSONAL_REGISTO" ADD CONSTRAINT "SYS_C007056" CHECK ("APELLIDOS" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."PERSONAL_REGISTO" ADD CONSTRAINT "SYS_C007057" CHECK ("TELEFONO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."PERSONAL_REGISTO" ADD CONSTRAINT "SYS_C007058" CHECK ("DIRECCION" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."PERSONAL_REGISTO" ADD CONSTRAINT "SYS_C007059" CHECK ("LATITUD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."PERSONAL_REGISTO" ADD CONSTRAINT "SYS_C007060" CHECK ("LONGITUD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."PERSONAL_REGISTO" ADD CONSTRAINT "SYS_C007061" CHECK ("FECHA_NACIMIENTO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table PLANES_ESTUDIOS
-- ----------------------------
ALTER TABLE "JC"."PLANES_ESTUDIOS" ADD CONSTRAINT "SYS_C007064" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table PLANES_ESTUDIOS
-- ----------------------------
ALTER TABLE "JC"."PLANES_ESTUDIOS" ADD CONSTRAINT "SYS_C007063" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table PREGUNTAS_BREVES
-- ----------------------------
ALTER TABLE "JC"."PREGUNTAS_BREVES" ADD CONSTRAINT "SYS_C007068" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table PREGUNTAS_BREVES
-- ----------------------------
ALTER TABLE "JC"."PREGUNTAS_BREVES" ADD CONSTRAINT "SYS_C007065" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table PREGUNTAS_MULTIPLES
-- ----------------------------
ALTER TABLE "JC"."PREGUNTAS_MULTIPLES" ADD CONSTRAINT "SYS_C007069" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table PREGUNTAS_MULTIPLES
-- ----------------------------
ALTER TABLE "JC"."PREGUNTAS_MULTIPLES" ADD CONSTRAINT "SYS_C007066" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table PREGUNTAS_PRUEBAS_SECCIONES
-- ----------------------------
ALTER TABLE "JC"."PREGUNTAS_PRUEBAS_SECCIONES" ADD CONSTRAINT "SYS_C007070" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table PREGUNTAS_PRUEBAS_SECCIONES
-- ----------------------------
ALTER TABLE "JC"."PREGUNTAS_PRUEBAS_SECCIONES" ADD CONSTRAINT "SYS_C007067" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table PREGUNTAS_VOFS
-- ----------------------------
ALTER TABLE "JC"."PREGUNTAS_VOFS" ADD CONSTRAINT "SYS_C007080" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table PREGUNTAS_VOFS
-- ----------------------------
ALTER TABLE "JC"."PREGUNTAS_VOFS" ADD CONSTRAINT "SYS_C007071" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table PRUEBAS_ALUMNOS
-- ----------------------------
ALTER TABLE "JC"."PRUEBAS_ALUMNOS" ADD CONSTRAINT "SYS_C007084" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table PRUEBAS_ALUMNOS
-- ----------------------------
ALTER TABLE "JC"."PRUEBAS_ALUMNOS" ADD CONSTRAINT "SYS_C007072" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table PRUEBAS_SECCIONES
-- ----------------------------
ALTER TABLE "JC"."PRUEBAS_SECCIONES" ADD CONSTRAINT "SYS_C007083" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table PRUEBAS_SECCIONES
-- ----------------------------
ALTER TABLE "JC"."PRUEBAS_SECCIONES" ADD CONSTRAINT "SYS_C007073" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table RECLAMOS
-- ----------------------------
ALTER TABLE "JC"."RECLAMOS" ADD CONSTRAINT "SYS_C007082" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table RECLAMOS
-- ----------------------------
ALTER TABLE "JC"."RECLAMOS" ADD CONSTRAINT "SYS_C007074" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table RESPUESTAS_BREVES
-- ----------------------------
ALTER TABLE "JC"."RESPUESTAS_BREVES" ADD CONSTRAINT "SYS_C007081" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table RESPUESTAS_BREVES
-- ----------------------------
ALTER TABLE "JC"."RESPUESTAS_BREVES" ADD CONSTRAINT "SYS_C007075" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table RESPUESTAS_FOROS
-- ----------------------------
ALTER TABLE "JC"."RESPUESTAS_FOROS" ADD CONSTRAINT "SYS_C007079" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table RESPUESTAS_FOROS
-- ----------------------------
ALTER TABLE "JC"."RESPUESTAS_FOROS" ADD CONSTRAINT "SYS_C007076" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table RESPUESTAS_MULTIPLES
-- ----------------------------
ALTER TABLE "JC"."RESPUESTAS_MULTIPLES" ADD CONSTRAINT "SYS_C007156" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table RESPUESTAS_MULTIPLES
-- ----------------------------
ALTER TABLE "JC"."RESPUESTAS_MULTIPLES" ADD CONSTRAINT "SYS_C007110" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table RESPUESTAS_PRUEBAS_ALUMNOS
-- ----------------------------
ALTER TABLE "JC"."RESPUESTAS_PRUEBAS_ALUMNOS" ADD CONSTRAINT "SYS_C007078" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table RESPUESTAS_PRUEBAS_ALUMNOS
-- ----------------------------
ALTER TABLE "JC"."RESPUESTAS_PRUEBAS_ALUMNOS" ADD CONSTRAINT "SYS_C007077" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table RESPUESTAS_VOFS
-- ----------------------------
ALTER TABLE "JC"."RESPUESTAS_VOFS" ADD CONSTRAINT "SYS_C007088" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table RESPUESTAS_VOFS
-- ----------------------------
ALTER TABLE "JC"."RESPUESTAS_VOFS" ADD CONSTRAINT "SYS_C007085" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table SALDOS
-- ----------------------------
ALTER TABLE "JC"."SALDOS" ADD CONSTRAINT "SYS_C007087" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table SALDOS
-- ----------------------------
ALTER TABLE "JC"."SALDOS" ADD CONSTRAINT "SYS_C007086" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table SECCIONES
-- ----------------------------
ALTER TABLE "JC"."SECCIONES" ADD CONSTRAINT "SYS_C007094" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table SECCIONES
-- ----------------------------
ALTER TABLE "JC"."SECCIONES" ADD CONSTRAINT "SYS_C007089" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table SEDES
-- ----------------------------
ALTER TABLE "JC"."SEDES" ADD CONSTRAINT "SYS_C007093" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table SEDES
-- ----------------------------
ALTER TABLE "JC"."SEDES" ADD CONSTRAINT "SYS_C007090" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table TAREAS_ALUMNOS
-- ----------------------------
ALTER TABLE "JC"."TAREAS_ALUMNOS" ADD CONSTRAINT "SYS_C007092" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table TAREAS_ALUMNOS
-- ----------------------------
ALTER TABLE "JC"."TAREAS_ALUMNOS" ADD CONSTRAINT "SYS_C007091" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table TAREAS_SECCIONES
-- ----------------------------
ALTER TABLE "JC"."TAREAS_SECCIONES" ADD CONSTRAINT "SYS_C007096" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table TAREAS_SECCIONES
-- ----------------------------
ALTER TABLE "JC"."TAREAS_SECCIONES" ADD CONSTRAINT "SYS_C007095" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table TIPOS_DE_USUARIO
-- ----------------------------
ALTER TABLE "JC"."TIPOS_DE_USUARIO" ADD CONSTRAINT "SYS_C007106" PRIMARY KEY ("TIPO_USUARIO");

-- ----------------------------
-- Checks structure for table TIPOS_DE_USUARIO
-- ----------------------------
ALTER TABLE "JC"."TIPOS_DE_USUARIO" ADD CONSTRAINT "SYS_C007097" CHECK ("TIPO_USUARIO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."TIPOS_DE_USUARIO" ADD CONSTRAINT "SYS_C007098" CHECK ("DESCRIPCION" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table TIPOS_RECLAMOS
-- ----------------------------
ALTER TABLE "JC"."TIPOS_RECLAMOS" ADD CONSTRAINT "SYS_C007105" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table TIPOS_RECLAMOS
-- ----------------------------
ALTER TABLE "JC"."TIPOS_RECLAMOS" ADD CONSTRAINT "SYS_C007099" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table USUARIOS
-- ----------------------------
ALTER TABLE "JC"."USUARIOS" ADD CONSTRAINT "SYS_C007104" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table USUARIOS
-- ----------------------------
ALTER TABLE "JC"."USUARIOS" ADD CONSTRAINT "SYS_C007100" CHECK ("CORREO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."USUARIOS" ADD CONSTRAINT "SYS_C007101" CHECK ("PASSWORD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."USUARIOS" ADD CONSTRAINT "SYS_C007102" CHECK ("FK_TIPO_USUARIO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."USUARIOS" ADD CONSTRAINT "SYS_C007103" CHECK ("ESTADO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table ACTIVIDADES_CLASES
-- ----------------------------
ALTER TABLE "JC"."ACTIVIDADES_CLASES" ADD CONSTRAINT "SYS_C007129" FOREIGN KEY ("FK_SECCION") REFERENCES "JC"."SECCIONES" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."ACTIVIDADES_CLASES" ADD CONSTRAINT "SYS_C007130" FOREIGN KEY ("FK_MODALIDAD") REFERENCES "JC"."MODALIDADES" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table ALUMNOS
-- ----------------------------
ALTER TABLE "JC"."ALUMNOS" ADD CONSTRAINT "SYS_C007118" FOREIGN KEY ("FK_USUARIO") REFERENCES "JC"."USUARIOS" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table ALUMNOS_SECCIONES
-- ----------------------------
ALTER TABLE "JC"."ALUMNOS_SECCIONES" ADD CONSTRAINT "SYS_C007131" FOREIGN KEY ("FK_ALUMNO") REFERENCES "JC"."ALUMNOS" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."ALUMNOS_SECCIONES" ADD CONSTRAINT "SYS_C007132" FOREIGN KEY ("FK_SEECION") REFERENCES "JC"."SECCIONES" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table ARREGLOS_PAGOS
-- ----------------------------
ALTER TABLE "JC"."ARREGLOS_PAGOS" ADD CONSTRAINT "SYS_C007138" FOREIGN KEY ("FK_ESTUDIANTE") REFERENCES "JC"."ALUMNOS" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table CARRERAS
-- ----------------------------
ALTER TABLE "JC"."CARRERAS" ADD CONSTRAINT "SYS_C007120" FOREIGN KEY ("FK_PLAN") REFERENCES "JC"."PLANES_ESTUDIOS" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."CARRERAS" ADD CONSTRAINT "SYS_C007121" FOREIGN KEY ("FK_ORIENTACION") REFERENCES "JC"."ORIENTACIONES" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table CARRERAS_ALUMNOS
-- ----------------------------
ALTER TABLE "JC"."CARRERAS_ALUMNOS" ADD CONSTRAINT "SYS_C007122" FOREIGN KEY ("FK_CARRERA") REFERENCES "JC"."CARRERAS" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."CARRERAS_ALUMNOS" ADD CONSTRAINT "SYS_C007123" FOREIGN KEY ("FK_IDENTIDAD_ALUMNO") REFERENCES "JC"."ALUMNOS" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table CLASES_PLANES_ESTUDIO
-- ----------------------------
ALTER TABLE "JC"."CLASES_PLANES_ESTUDIO" ADD CONSTRAINT "SYS_C007133" FOREIGN KEY ("FK_PLAN") REFERENCES "JC"."PLANES_ESTUDIOS" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."CLASES_PLANES_ESTUDIO" ADD CONSTRAINT "SYS_C007134" FOREIGN KEY ("FK_CLASE") REFERENCES "JC"."CLASES" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table FORO_SECCIONES
-- ----------------------------
ALTER TABLE "JC"."FORO_SECCIONES" ADD CONSTRAINT "SYS_C007146" FOREIGN KEY ("FK_SECCION") REFERENCES "JC"."SECCIONES" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."FORO_SECCIONES" ADD CONSTRAINT "SYS_C007147" FOREIGN KEY ("FK_MAESTRO") REFERENCES "JC"."MAESTROS" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table MAESTROS
-- ----------------------------
ALTER TABLE "JC"."MAESTROS" ADD CONSTRAINT "SYS_C007119" FOREIGN KEY ("FK_USUARIO") REFERENCES "JC"."USUARIOS" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table PAGOS
-- ----------------------------
ALTER TABLE "JC"."PAGOS" ADD CONSTRAINT "SYS_C007137" FOREIGN KEY ("FK_ALUMNO") REFERENCES "JC"."ALUMNOS" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table PERSONAL_REGISTO
-- ----------------------------
ALTER TABLE "JC"."PERSONAL_REGISTO" ADD CONSTRAINT "SYS_C007139" FOREIGN KEY ("FK_USUARIO") REFERENCES "JC"."USUARIOS" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table PREGUNTAS_PRUEBAS_SECCIONES
-- ----------------------------
ALTER TABLE "JC"."PREGUNTAS_PRUEBAS_SECCIONES" ADD CONSTRAINT "SYS_C007148" FOREIGN KEY ("FK_PREGUNTA_VOF") REFERENCES "JC"."PREGUNTAS_VOFS" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."PREGUNTAS_PRUEBAS_SECCIONES" ADD CONSTRAINT "SYS_C007149" FOREIGN KEY ("FK_PRUEBA_SECCION") REFERENCES "JC"."PRUEBAS_SECCIONES" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."PREGUNTAS_PRUEBAS_SECCIONES" ADD CONSTRAINT "SYS_C007150" FOREIGN KEY ("FK_PREGUNTA_MULT") REFERENCES "JC"."PREGUNTAS_MULTIPLES" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."PREGUNTAS_PRUEBAS_SECCIONES" ADD CONSTRAINT "SYS_C007151" FOREIGN KEY ("FK_PREGUNTA_BREVE") REFERENCES "JC"."PREGUNTAS_BREVES" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table PRUEBAS_ALUMNOS
-- ----------------------------
ALTER TABLE "JC"."PRUEBAS_ALUMNOS" ADD CONSTRAINT "SYS_C007152" FOREIGN KEY ("FK_PRUEBA_SECCION") REFERENCES "JC"."PRUEBAS_SECCIONES" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."PRUEBAS_ALUMNOS" ADD CONSTRAINT "SYS_C007153" FOREIGN KEY ("FK_ALUMNO") REFERENCES "JC"."ALUMNOS" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table PRUEBAS_SECCIONES
-- ----------------------------
ALTER TABLE "JC"."PRUEBAS_SECCIONES" ADD CONSTRAINT "SYS_C007143" FOREIGN KEY ("FK_SECCION") REFERENCES "JC"."SECCIONES" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."PRUEBAS_SECCIONES" ADD CONSTRAINT "SYS_C007144" FOREIGN KEY ("FK_MAESTRO") REFERENCES "JC"."MAESTROS" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table RECLAMOS
-- ----------------------------
ALTER TABLE "JC"."RECLAMOS" ADD CONSTRAINT "SYS_C007135" FOREIGN KEY ("FK_DOCENTE") REFERENCES "JC"."MAESTROS" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."RECLAMOS" ADD CONSTRAINT "SYS_C007136" FOREIGN KEY ("FK_TIPO_RECLAMO") REFERENCES "JC"."TIPOS_RECLAMOS" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table RESPUESTAS_FOROS
-- ----------------------------
ALTER TABLE "JC"."RESPUESTAS_FOROS" ADD CONSTRAINT "SYS_C007154" FOREIGN KEY ("FK_FORO") REFERENCES "JC"."FORO_SECCIONES" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."RESPUESTAS_FOROS" ADD CONSTRAINT "SYS_C007155" FOREIGN KEY ("FK_ALUMNO") REFERENCES "JC"."ALUMNOS" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table RESPUESTAS_PRUEBAS_ALUMNOS
-- ----------------------------
ALTER TABLE "JC"."RESPUESTAS_PRUEBAS_ALUMNOS" ADD CONSTRAINT "SYS_C007157" FOREIGN KEY ("FK_RESPUESTA_ALUMNO") REFERENCES "JC"."ALUMNOS" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."RESPUESTAS_PRUEBAS_ALUMNOS" ADD CONSTRAINT "SYS_C007158" FOREIGN KEY ("FK_RESPUESTA_BREVE") REFERENCES "JC"."RESPUESTAS_BREVES" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."RESPUESTAS_PRUEBAS_ALUMNOS" ADD CONSTRAINT "SYS_C007159" FOREIGN KEY ("FK_RESPUESTA_MULTI") REFERENCES "JC"."RESPUESTAS_MULTIPLES" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."RESPUESTAS_PRUEBAS_ALUMNOS" ADD CONSTRAINT "SYS_C007160" FOREIGN KEY ("FK_RESPUESTA_VOF") REFERENCES "JC"."RESPUESTAS_VOFS" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table SALDOS
-- ----------------------------
ALTER TABLE "JC"."SALDOS" ADD CONSTRAINT "SYS_C007142" FOREIGN KEY ("FK_ALUMNO") REFERENCES "JC"."ALUMNOS" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table SECCIONES
-- ----------------------------
ALTER TABLE "JC"."SECCIONES" ADD CONSTRAINT "SYS_C007124" FOREIGN KEY ("FK_CODIGO_CLASE") REFERENCES "JC"."CLASES" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."SECCIONES" ADD CONSTRAINT "SYS_C007125" FOREIGN KEY ("FK_DOCENTE") REFERENCES "JC"."MAESTROS" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."SECCIONES" ADD CONSTRAINT "SYS_C007126" FOREIGN KEY ("FK_SEDE") REFERENCES "JC"."SEDES" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."SECCIONES" ADD CONSTRAINT "SYS_C007127" FOREIGN KEY ("FK_PERIODO_ACTUAL") REFERENCES "JC"."PERIODO_ACTUAL" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."SECCIONES" ADD CONSTRAINT "SYS_C007128" FOREIGN KEY ("FK_MODALIDAD") REFERENCES "JC"."MODALIDADES" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table SEDES
-- ----------------------------
ALTER TABLE "JC"."SEDES" ADD CONSTRAINT "SYS_C007145" FOREIGN KEY ("FK_ID_UNIVERSIDAD") REFERENCES "JC"."INFO_UNIVERIDADES" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table TAREAS_ALUMNOS
-- ----------------------------
ALTER TABLE "JC"."TAREAS_ALUMNOS" ADD CONSTRAINT "SYS_C007161" FOREIGN KEY ("FK_TAREA") REFERENCES "JC"."TAREAS_SECCIONES" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."TAREAS_ALUMNOS" ADD CONSTRAINT "SYS_C007162" FOREIGN KEY ("FK_ALUMNO") REFERENCES "JC"."ALUMNOS" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table TAREAS_SECCIONES
-- ----------------------------
ALTER TABLE "JC"."TAREAS_SECCIONES" ADD CONSTRAINT "SYS_C007140" FOREIGN KEY ("FK_SECCION") REFERENCES "JC"."SECCIONES" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "JC"."TAREAS_SECCIONES" ADD CONSTRAINT "SYS_C007141" FOREIGN KEY ("FK_DOCENTE") REFERENCES "JC"."MAESTROS" ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table USUARIOS
-- ----------------------------
ALTER TABLE "JC"."USUARIOS" ADD CONSTRAINT "SYS_C007107" FOREIGN KEY ("FK_TIPO_USUARIO") REFERENCES "JC"."TIPOS_DE_USUARIO" ("TIPO_USUARIO") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
